TopologyAPI
std::string TopologyAPI::connectionID
QUERY TopologyAPI::currentQuery
std::vector<Topology*> TopologyAPI::topologies
bool TopologyAPI::chech_path(std::string filePath)
TopologyAPI::TopologyAPI(void)
References HELP, randomString.
TopologyAPI::TopologyAPI(QUERY currentQuery)
References randomString.
TopologyAPI::TopologyAPI(std::string filePath)
References HELP, randomString.
TopologyAPI::TopologyAPI(QUERY currentQuery, std::string filePath)
References randomString.
std::string TopologyAPI::randomString(void)
Referenced by TopologyAPI.
std::string TopologyAPI::getConnectionID(void)
QUERY TopologyAPI::getCurrentQuery(void)
int TopologyAPI::getNumberOfTopologies(void)
std::vector< Topology * > * TopologyAPI::getTopologies(void)
Referenced by TopologyAPIUnitTest::TestQuery3, TopologyAPIUnitTest::TestQuery4, TopologyAPIUnitTest::TestQuery5, TopologyAPIUnitTest::TestQuery6.
void TopologyAPI::addTopology(Topology *topology)
Referenced by createTopology, readJson, TopologyAPIUnitTest::TestQuery2, TopologyAPIUnitTest::TestQuery3, TopologyAPIUnitTest::TestQuery4, TopologyAPIUnitTest::TestQuery5, TopologyAPIUnitTest::TestQuery6.
void TopologyAPI::setCurrentQuery(QUERY currentQuery)
void TopologyAPI::createTopology(void)
References Topology::addComponent, addTopology, Component::get_type, Device::set_defaultValue, Component::set_device, Device::set_maxValue, Device::set_minValue, Component::set_netlist, Component::set_type.
Referenced by executeQuery.
void TopologyAPI::executeQuery(TopologyAPI_Param *parameter)
References CREATE, createTopology, DELETE, deleteTopology, TopologyAPI_Param::filePath, HELP, help, IS_CONNECTED, TopologyAPI_Param::node, queryDevices, queryDevicesWithNetlistNode, queryTopologies, READ, readJson, TopologyAPI_Param::topologyID, WHICH_DEVICES, WHICH_TOPOLOGIES, WRITE, writeJSON.
void TopologyAPI::help(void)
Referenced by executeQuery.
bool TopologyAPI::readJson(std::string filePath)
References Topology::addComponent, addTopology, Component::set_device, Component::set_netlist.
Referenced by executeQuery, TopologyAPIUnitTest::TestQuery1, TopologyAPIUnitTest::TestQuery3.
bool TopologyAPI::writeJSON(std::string filePath, std::string topologyID)
References Topology::getComponents, Topology::getID.
Referenced by executeQuery, TopologyAPIUnitTest::TestQuery2.
std::vector< Topology * > * TopologyAPI::queryTopologies(void)
Referenced by executeQuery, TopologyAPIUnitTest::TestQuery3, TopologyAPIUnitTest::TestQuery4.
bool TopologyAPI::deleteTopology(std::string topologyID)
Referenced by executeQuery, TopologyAPIUnitTest::TestQuery3, TopologyAPIUnitTest::TestQuery4, TopologyAPIUnitTest::TestQuery5, TopologyAPIUnitTest::TestQuery6.
std::vector< Device * > * TopologyAPI::queryDevices(std::string topologyID)
References Topology::getComponents, Topology::print.
Referenced by executeQuery, TopologyAPIUnitTest::TestQuery5.
std::vector< Device * > * TopologyAPI::queryDevicesWithNetlistNode(std::string topologyID, std::string node)
References Topology::getComponents.
Referenced by executeQuery, TopologyAPIUnitTest::TestQuery6.
TopologyAPI::~TopologyAPI(void)