Topology
std::string Topology::id
std::vector<Component*>* Topology::components
Topology::Topology(std::string id)
Topology::Topology(std::string id, std::vector< Component * > components)
References setComponents.
void Topology::setID(std::string id)
void Topology::setComponents(std::vector< Component * > components)
Referenced by Topology.
std::string Topology::getID(void)
Referenced by TopologyAPIUnitTest::TestQuery2, TopologyAPIUnitTest::TestQuery4, TopologyAPIUnitTest::TestQuery5, TopologyAPIUnitTest::TestQuery6, TopologyAPI::writeJSON.
std::vector< Component * > * Topology::getComponents(void)
Referenced by TopologyAPI::queryDevices, TopologyAPI::queryDevicesWithNetlistNode, TopologyAPI::writeJSON.
void Topology::addComponent(Component *component)
Referenced by TopologyAPI::createTopology, TopologyAPI::readJson, TopologyAPIUnitTest::TestQuery2, TopologyAPIUnitTest::TestQuery3, TopologyAPIUnitTest::TestQuery4, TopologyAPIUnitTest::TestQuery5, TopologyAPIUnitTest::TestQuery6.
void Topology::print(void)
Referenced by TopologyAPI::queryDevices.
Topology::~Topology(void)