Component
std::string Component::type
std::string Component::id
Device* Component::device
std::unordered_map<std::string, std::string> Component::netlist
Component::Component(std::string type, std::string id)
Component::Component(std::string id)
Component::Component(std::string type, std::string id, Device *device)
Component::Component(std::string type, std::string id, Device *device, std::unordered_map< std::string, std::string > &netlist)
References set_netlist.
void Component::set_type(std::string type)
Referenced by TopologyAPI::createTopology.
void Component::set_id(std::string id)
void Component::set_device(Device *device)
Referenced by TopologyAPI::createTopology, TopologyAPI::readJson.
void Component::set_netlist(std::unordered_map< std::string, std::string > &netlist)
Referenced by Component, TopologyAPI::createTopology, TopologyAPI::readJson.
std::string Component::get_type(void)
Referenced by TopologyAPI::createTopology.
std::string Component::get_id(void)
Device * Component::get_device(void)
std::unordered_map< std::string, std::string > * Component::get_netlist(void)
void Component::print(void)
References Device::print.
Component::~Component(void)