TopologyAPIUnitTest
TopologyAPI* TopologyAPIUnitTest::connection
TopologyAPIUnitTest::TopologyAPIUnitTest(void)
void TopologyAPIUnitTest::TestQuery1(void)
References TopologyAPI::readJson.
Referenced by unitTesting.
void TopologyAPIUnitTest::TestQuery2(void)
References Topology::addComponent, TopologyAPI::addTopology, Topology::getID, TopologyAPI::writeJSON.
Referenced by unitTesting.
void TopologyAPIUnitTest::TestQuery3(void)
References Topology::addComponent, TopologyAPI::addTopology, TopologyAPI::deleteTopology, TopologyAPI::getTopologies, TopologyAPI::queryTopologies, TopologyAPI::readJson.
Referenced by unitTesting.
void TopologyAPIUnitTest::TestQuery4(void)
References Topology::addComponent, TopologyAPI::addTopology, TopologyAPI::deleteTopology, Topology::getID, TopologyAPI::getTopologies, TopologyAPI::queryTopologies.
Referenced by unitTesting.
void TopologyAPIUnitTest::TestQuery5(void)
References Topology::addComponent, TopologyAPI::addTopology, TopologyAPI::deleteTopology, Topology::getID, TopologyAPI::getTopologies, TopologyAPI::queryDevices.
Referenced by unitTesting.
void TopologyAPIUnitTest::TestQuery6(void)
References Topology::addComponent, TopologyAPI::addTopology, TopologyAPI::deleteTopology, Topology::getID, TopologyAPI::getTopologies, TopologyAPI::queryDevicesWithNetlistNode.
Referenced by unitTesting.
TopologyAPIUnitTest::~TopologyAPIUnitTest(void)