Device
std::string Device::name
float Device::defaultValue
float Device::minValue
float Device::maxValue
Device::Device(std::string name)
Device::Device(std::string name, float defaultValue)
Device::Device(std::string name, float defaultValue, float minValue)
Device::Device(std::string name, float defaultValue, float minValue, float maxValue)
void Device::set_name(std::string name)
void Device::set_defaultValue(float defaultValue)
Referenced by TopologyAPI::createTopology.
void Device::set_minValue(float minValue)
Referenced by TopologyAPI::createTopology.
void Device::set_maxValue(float maxValue)
Referenced by TopologyAPI::createTopology.
std::string Device::get_name(void)
float Device::get_defaultValue(void)
float Device::get_minValue(void)
float Device::get_maxValue(void)
void Device::print(void)
Referenced by Component::print, NMOS::print, Resistor::print.
Device::~Device(void)